# Generated by Django 3.0.8 on 2020-07-28 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20200728_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='reply',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Blog.Comments'),
            preserve_default='True',
        ),
    ]
